DELETE http://localhost:3000/user/68b88066f1ed134781c97d74/deleteproducts
Content-Type: application/json

{
    "productID": "68cafc65951c73cba73ee9c6"
}

###
PATCH  http://localhost:3000/user/68b1ed11b29724410b641a6a/addproducts
Content-Type: application/json

{
    "productId": "68af34d4833e1d4080f93d8d"
}


###
POST http://localhost:3000/estoque

Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="image"; filename="3090.jpg"
Content-Type: image/jpeg

< C:/Users/vitor/OneDrive/Imagens/Saved Pictures/teclado.jpeg
------MyBoundary
Content-Disposition: form-data; name="name"

Teclado Mecânico
------MyBoundary
Content-Disposition: form-data; name="unitsAvailable"

12
------MyBoundary
Content-Disposition: form-data; name="priceUnit"

219
------MyBoundary
Content-Disposition: form-data; name="isAvailable"

true
------MyBoundary--




###
PATCH http://localhost:3000/estoque/68b05cab5e437deec45de3f0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWNjNTYyMmFlYzVhZDNkNTRhOGQ3MCIsImlhdCI6MTc1NjM4ODQzOX0.YaNQPcJk8rdO4WGHgF-6_9ovAvCDCU7d7n6Trxol9mw
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="unitsAvailable"

13
------MyBoundary--

###

DELETE  http://localhost:3000/estoque/68b05c6483cfdd36e27d6c1e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWNjNTYyMmFlYzVhZDNkNTRhOGQ3MCIsImlhdCI6MTc1NjM4ODQzOX0.YaNQPcJk8rdO4WGHgF-6_9ovAvCDCU7d7n6Trxol9mw
Content-Type: multipart/form-data; boundary=----MyBoundary


###

POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "jp",
    "email": "jp@gmail.com",
    "password": "1234",
    "confirmPassword": "1234",
    "role": "Requester"
}